#Banco de dados
---
    - name: Instalando dependencias do banco de dados
      ansible.builtin.apt:
        pkg:
        - mysql-server
        - python3-pymysql
        state: latest
        update_cache: yes
      become: yes
    - name: Criando a tabela Wordpress_db do banco de dados mysql
      community.mysql.mysql_db:
        name: '{{ wp_db_name }}'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
      become: yes

    - name: Criando usuário wordpress_user e criando a senha 12345 e colocandos os privilegios necessários
      community.mysql.mysql_user:
        name: '{{ wp_db_user }}'
        password: '{{ wp_db_pass }}'
        priv: '{{ wp_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
        host: '{{ item }}'
      with_items:
      - 'localhost'
      - '127.0.0.1'
      - '{{ wp_ip }}'
      become: yes
    - name: Modificar os arquivos de configuracao do mysql para acesso via rede
      ansible.builtin.replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"
      become: yes
      notify:
        - restart mysql #Nome do handler